import { Head, useForm } from '@inertiajs/react';
import { FormEvent } from 'react';
import AppLayout from '../../Layouts/AppLayout';
import { ErrorSummary, FieldError, FormShell, handleSmartLinkPaste, PageHeader } from '../../Components/UI';
import { inputDate } from '../../lib/format';

export default function Form({ entry, options }: any) {
  const form = useForm({ date: inputDate(entry?.date) || new Date().toISOString().slice(0, 10), topic: entry?.topic || '', category: entry?.category || 'programming', source_type: entry?.source_type || 'practice', duration_minutes: entry?.duration_minutes || 30, progress_notes: entry?.progress_notes || '', takeaway: entry?.takeaway || '', next_action: entry?.next_action || '', rating: entry?.rating || '' });
  const submit = (e: FormEvent) => { e.preventDefault(); entry ? form.put(route('learning.update', entry.id)) : form.post(route('learning.store')); };
  return <AppLayout><Head title={entry ? 'Edit learning' : 'New learning'} /><PageHeader title={entry ? 'Edit learning session' : 'New learning session'} backHref={entry ? route('learning.show', entry.id) : route('learning.index')} /><ErrorSummary errors={form.errors} /><form onSubmit={submit}><FormShell><Input form={form} name="date" type="date" /><Input form={form} name="topic" /><Select form={form} name="category" options={options.categories} /><Select form={form} name="source_type" options={options.sourceTypes} /><Input form={form} name="duration_minutes" type="number" /><Input form={form} name="rating" type="number" /><Area form={form} name="progress_notes" /><Area form={form} name="takeaway" /><Area form={form} name="next_action" wide /><div className="lg:col-span-2 flex justify-end"><button className="btn btn-primary" type="submit" disabled={form.processing}>{form.processing ? 'Saving...' : 'Save learning'}</button></div></FormShell></form></AppLayout>;
}
function Input({ form, name, type = 'text' }: any) { return <div><label className="label">{name.replaceAll('_', ' ')}</label><input className="field mt-1" type={type} value={form.data[name]} onChange={(e) => form.setData(name, e.target.value)} /><FieldError message={form.errors[name]} /></div>; }
function Select({ form, name, options }: any) { return <div><label className="label">{name.replaceAll('_', ' ')}</label><select className="field mt-1" value={form.data[name]} onChange={(e) => form.setData(name, e.target.value)}>{options.map((o: string) => <option key={o} value={o}>{o}</option>)}</select></div>; }
function Area({ form, name, wide = false }: any) { return <div className={wide ? 'lg:col-span-2' : ''}><label className="label">{name.replaceAll('_', ' ')}</label><textarea className="field mt-1 min-h-28" value={form.data[name]} onChange={(e) => form.setData(name, e.target.value)} onPaste={(e) => handleSmartLinkPaste(e, form.data[name], (value) => form.setData(name, value))} /><p className="mt-1 text-xs text-zinc-500">Select text, paste a URL, and it becomes a clickable reference.</p></div>; }
