import { Head, useForm } from '@inertiajs/react';
import { FormEvent } from 'react';
import AppLayout from '../../Layouts/AppLayout';
import { ErrorSummary, FieldError, FormShell, handleSmartLinkPaste, PageHeader } from '../../Components/UI';
import { inputDate } from '../../lib/format';

export default function Form({ milestone, options }: any) {
  const form = useForm({ title: milestone?.title || '', category: milestone?.category || 'career', target_type: milestone?.target_type || 'count', source_type: milestone?.source_type || 'manual', source_filter: milestone?.source_filter || '', target_value: milestone?.target_value || 1, current_value: milestone?.current_value || 0, start_date: inputDate(milestone?.start_date), end_date: inputDate(milestone?.end_date), status: milestone?.status || 'active', notes: milestone?.notes || '' });
  const submit = (e: FormEvent) => { e.preventDefault(); milestone ? form.put(route('milestones.update', milestone.id)) : form.post(route('milestones.store')); };
  return <AppLayout><Head title={milestone ? 'Edit milestone' : 'New milestone'} /><PageHeader title={milestone ? 'Edit milestone' : 'New milestone'} backHref={milestone ? route('milestones.show', milestone.id) : route('milestones.index')} /><ErrorSummary errors={form.errors} /><form onSubmit={submit}><FormShell><Input form={form} name="title" /><Input form={form} name="category" /><Select form={form} name="target_type" options={options.targetTypes} /><Select form={form} name="source_type" options={options.sourceTypes} /><Input form={form} name="source_filter" /><Select form={form} name="status" options={options.statuses} /><Input form={form} name="target_value" type="number" /><Input form={form} name="current_value" type="number" /><Input form={form} name="start_date" type="date" /><Input form={form} name="end_date" type="date" /><div className="lg:col-span-2"><label className="label">Notes</label><textarea className="field mt-1 min-h-32" value={form.data.notes} onChange={e => form.setData('notes', e.target.value)} onPaste={(e) => handleSmartLinkPaste(e, form.data.notes, (value) => form.setData('notes', value))} /><p className="mt-1 text-xs text-zinc-500">Select text, paste a URL, and it becomes a clickable reference.</p></div><div className="lg:col-span-2 flex justify-end"><button className="btn btn-primary" type="submit" disabled={form.processing}>{form.processing ? 'Saving...' : 'Save milestone'}</button></div></FormShell></form></AppLayout>;
}
function Input({ form, name, type = 'text' }: any) { return <div><label className="label">{name.replaceAll('_', ' ')}</label><input className="field mt-1" type={type} value={form.data[name]} onChange={(e) => form.setData(name, e.target.value)} /><FieldError message={form.errors[name]} /></div>; }
function Select({ form, name, options }: any) { return <div><label className="label">{name.replaceAll('_', ' ')}</label><select className="field mt-1" value={form.data[name]} onChange={(e) => form.setData(name, e.target.value)}>{options.map((o: string) => <option key={o} value={o}>{o}</option>)}</select></div>; }
