import { Head, useForm } from '@inertiajs/react';
import { FormEvent } from 'react';
import AppLayout from '../../Layouts/AppLayout';
import { ErrorSummary, FieldError, FormShell, handleSmartLinkPaste, PageHeader } from '../../Components/UI';
import { inputDate } from '../../lib/format';

export default function Form({ log, options }: any) {
  const form = useForm({ date: inputDate(log?.date) || new Date().toISOString().slice(0, 10), project_name: log?.project_name || '', ticket_code: log?.ticket_code || '', title: log?.title || '', category: log?.category || 'feature', status: log?.status || 'todo', priority: log?.priority || 'medium', description: log?.description || '', resolution_or_outcome: log?.resolution_or_outcome || '', estimated_duration: log?.estimated_duration || '', actual_duration: log?.actual_duration || '', tags: (log?.tags || []).map((t: any) => t.name).join(', ') });
  const submit = (e: FormEvent) => { e.preventDefault(); const payload: any = { ...form.data, tags: form.data.tags.split(',').map(s => s.trim()).filter(Boolean) }; log ? form.transform(() => payload).put(route('work-logs.update', log.id)) : form.transform(() => payload).post(route('work-logs.store')); };
  return <AppLayout><Head title={log ? 'Edit work log' : 'New work log'} /><PageHeader title={log ? 'Edit work log' : 'New work log'} backHref={log ? route('work-logs.show', log.id) : route('work-logs.index')} /><ErrorSummary errors={form.errors} /><form onSubmit={submit}><FormShell><Input form={form} name="date" type="date" /><Input form={form} name="project_name" /><Input form={form} name="ticket_code" /><Input form={form} name="title" /><Select form={form} name="category" options={options.categories} /><Select form={form} name="status" options={options.statuses} /><Select form={form} name="priority" options={options.priorities} /><Input form={form} name="tags" /><Input form={form} name="estimated_duration" type="number" /><Input form={form} name="actual_duration" type="number" /><Area form={form} name="description" /><Area form={form} name="resolution_or_outcome" /><div className="lg:col-span-2 flex justify-end"><button className="btn btn-primary" type="submit" disabled={form.processing}>{form.processing ? 'Saving...' : 'Save work log'}</button></div></FormShell></form></AppLayout>;
}
function Input({ form, name, type = 'text' }: any) { return <div><label className="label">{name.replaceAll('_', ' ')}</label><input className="field mt-1" type={type} value={form.data[name]} onChange={(e) => form.setData(name, e.target.value)} /><FieldError message={form.errors[name]} /></div>; }
function Select({ form, name, options }: any) { return <div><label className="label">{name}</label><select className="field mt-1" value={form.data[name]} onChange={(e) => form.setData(name, e.target.value)}>{options.map((o: string) => <option key={o} value={o}>{o}</option>)}</select></div>; }
function Area({ form, name }: any) { return <div><label className="label">{name.replaceAll('_', ' ')}</label><textarea className="field mt-1 min-h-32" value={form.data[name]} onChange={(e) => form.setData(name, e.target.value)} onPaste={(e) => handleSmartLinkPaste(e, form.data[name], (value) => form.setData(name, value))} /><p className="mt-1 text-xs text-zinc-500">Select text, paste a URL, and it becomes a clickable reference.</p></div>; }
