import { Head, Link, router } from '@inertiajs/react';
import AppLayout from '../../Layouts/AppLayout';
import { Empty, PageHeader, Pagination, Stat, Tags } from '../../Components/UI';
import { formatDate, minutes } from '../../lib/format';

export default function Index({ logs, filters, summary }: any) {
  return <AppLayout><Head title="Work Logs" /><PageHeader title="Work Logs" action={<Link className="btn btn-primary" href={route('work-logs.create')}>Quick add</Link>} />
    <div className="mb-4 grid grid-cols-2 gap-3 lg:grid-cols-4">{['todo', 'in_progress', 'done', 'blocked'].map((s, i) => <Stat key={s} label={s.replace('_', ' ')} value={summary[s] || 0} tone={(['neutral', 'sky', 'teal', 'rose'] as any)[i]} />)}</div><Filters filters={filters} />
    {logs.data.length === 0 ? <Empty text="No work logs match this view." /> : <>
      <div className="mobile-card-list md:hidden">{logs.data.map((l: any) => <Link key={l.id} href={route('work-logs.show', l.id)} className="mobile-record"><div className="mb-2 flex items-start justify-between gap-3"><div><p className="font-semibold">{l.title}</p><p className="mt-1 text-sm text-slate-500">{l.project_name} · {formatDate(l.date)}</p></div><span className="rounded-md bg-slate-100 px-2 py-1 text-xs font-bold text-slate-600">{l.status}</span></div><div className="mb-3 text-sm text-slate-500">{minutes(l.actual_duration)}{l.ticket_code && ` · ${l.ticket_code}`}</div><Tags tags={l.tags} /></Link>)}</div>
      <div className="table-wrap hidden md:block"><table className="data-table"><thead><tr><th>Date</th><th>Project</th><th>Title</th><th>Status</th><th>Time</th><th>Tags</th></tr></thead><tbody>{logs.data.map((l: any) => <tr key={l.id}><td className="font-medium text-zinc-500">{formatDate(l.date)}</td><td>{l.project_name}</td><td><Link className="font-semibold hover:text-teal-700" href={route('work-logs.show', l.id)}>{l.ticket_code && <span className="mr-2 rounded bg-zinc-100 px-2 py-1 text-xs text-zinc-600 dark:bg-zinc-800">{l.ticket_code}</span>}{l.title}</Link></td><td><span className="rounded-md bg-zinc-100 px-2 py-1 text-xs font-bold dark:bg-zinc-800">{l.status}</span></td><td>{minutes(l.actual_duration)}</td><td><Tags tags={l.tags} /></td></tr>)}</tbody></table></div>
    </>}<Pagination links={logs.links} /></AppLayout>;
}
function Filters({ filters }: any) { return <form className="card mb-4 grid gap-3 p-4 md:grid-cols-5" onSubmit={e => { e.preventDefault(); router.get(route('work-logs.index'), Object.fromEntries(new FormData(e.currentTarget))); }}><input className="field" name="search" placeholder="Search" defaultValue={filters.search || ''} /><input className="field" name="project" placeholder="Project" defaultValue={filters.project || ''} /><select className="field" name="status" defaultValue={filters.status || ''}><option value="">Any status</option><option value="todo">todo</option><option value="in_progress">in progress</option><option value="done">done</option><option value="blocked">blocked</option></select><input className="field" name="category" placeholder="Category" defaultValue={filters.category || ''} /><button className="btn btn-muted">Filter</button></form>; }
